#!/usr/bin/env bash
echo "=== which / command -v ==="
which opencode 2>/dev/null || echo "(which: not found)"
command -v opencode || echo "(command -v: not found)"
echo "=== common locations ==="
ls -la ~/.local/bin/opencode 2>/dev/null || echo "(~/.local/bin/opencode: none)"
ls -la /usr/local/bin/opencode 2>/dev/null || echo "(/usr/local/bin/opencode: none)"
ls -la /usr/bin/opencode 2>/dev/null || echo "(/usr/bin/opencode: none)"
echo "=== PATH ==="
echo "$PATH"
echo "=== npm global root ==="
NPM_ROOT=$(npm root -g 2>/dev/null)
echo "npm root -g: $NPM_ROOT"
ls "$NPM_ROOT" 2>/dev/null | grep -i opencode || echo "(no opencode in npm global)"
echo "=== npm global bin ==="
NPM_BIN=$(npm bin -g 2>/dev/null || npm prefix -g 2>/dev/null)
echo "npm prefix -g: $NPM_BIN"
ls -la "$NPM_BIN/opencode" 2>/dev/null || echo "(no opencode bin in npm global prefix)"
echo "=== login shell rc grep ==="
grep -nH 'opencode' ~/.bashrc ~/.profile ~/.bash_profile ~/.zshrc 2>/dev/null || echo "(no opencode ref in rc files)"
